version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Por defecto docker busca el archivo .env
      POSTGRES_DB: ${DB_NAME}
    # Nombre del contenedor
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

# Con el - al principio debe finalizar con =
#environment
# - POSTGRES_PASSWORD=

#environment
# POSTGRES_PASSWORD: